    - name: Install apache
      apt: pkg=apache2
      sudo: yes
      notify:
      - Disable default VirtualHost
      - Set ServerName
      - Restart apache

    - name: Add pixijs sandbox game virtual host
      lineinfile: dest=/etc/apache2/sites-available/pixijs-sandbox.conf line="{{ item }}" owner=www-data group=www-data create=yes
      sudo: yes
      with_items:
      - "<VirtualHost *:80>"
      - "    ServerName pixijs-sandbox.qual.is"
      - "    DocumentRoot /home/vagrant/pixijs-sandbox"
      - "    DirectoryIndex index.html"
      - ""
      - "    <Directory />"
      - "        Options FollowSymLinks"
      - "        AllowOverride None"
      - "        Require all granted"
      - "    </Directory>"
      - "</VirtualHost>"

    - name: Enable VirtualHost
      shell: a2ensite pixijs-sandbox
      sudo: yes
      notify:
      - Restart apache
